#!/bin/bash
#This script migrates djangopostres

yum -y install python-pip
pip install virtualenv
pip install --upgrade pip

#make a dir on root called myproject, cd into it, activate, and run from inside 
mkdir ~/myproject
cd ~/myproject
virtualenv myprojectenv

#
source myprojectenv/bin/activate
pip install django psycopg2
django-admin.py startproject myproject .



wget -O ~/myproject/myproject/settings.py https://github.com/Hoangdinh85/NTI-310/blob/master/settings.py

python manage.py makemigrations
python manage.py migrate
