#!/bin/bash
#this script spins up an rsyslog client

#Client automation
yum -y update && yum -y install rsyslog
systemctl start rsyslog
systemctl enable rsyslog


#sending the logs to rsyslog
echo "*.* @@rsyslog:514" >> /etc/rsyslog.conf
systemctl restart rsyslog
